spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springboot_demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: sdjin942
  jpa:
    show-sql: true
